package com.utree.eightysix.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.utree.eightysix.dao.Conversation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table CONVERSATION.
 */
public class ConversationDao extends AbstractDao<Conversation, Long> {

    public static final String TABLENAME = "CONVERSATION";

    /**
     * Properties of entity Conversation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ChatId = new Property(1, String.class, "chatId", false, "CHAT_ID");
        public final static Property PostId = new Property(2, String.class, "postId", false, "POST_ID");
        public final static Property CommentId = new Property(3, String.class, "commentId", false, "COMMENT_ID");
        public final static Property LastMsg = new Property(4, String.class, "lastMsg", false, "LAST_MSG");
        public final static Property Portrait = new Property(5, String.class, "portrait", false, "PORTRAIT");
        public final static Property BgUrl = new Property(6, String.class, "bgUrl", false, "BG_URL");
        public final static Property PostContent = new Property(7, String.class, "postContent", false, "POST_CONTENT");
        public final static Property ChatSource = new Property(8, String.class, "chatSource", false, "CHAT_SOURCE");
        public final static Property Relation = new Property(9, String.class, "relation", false, "RELATION");
        public final static Property Timestamp = new Property(10, Long.class, "timestamp", false, "TIMESTAMP");
        public final static Property UnreadCount = new Property(11, Integer.class, "unreadCount", false, "UNREAD_COUNT");
        public final static Property Favorite = new Property(12, Boolean.class, "favorite", false, "FAVORITE");
    }

    ;


    public ConversationDao(DaoConfig config) {
        super(config);
    }

    public ConversationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'CONVERSATION' (" + //
            "'_id' INTEGER PRIMARY KEY ," + // 0: id
            "'CHAT_ID' TEXT," + // 1: chatId
            "'POST_ID' TEXT," + // 2: postId
            "'COMMENT_ID' TEXT," + // 3: commentId
            "'LAST_MSG' TEXT," + // 4: lastMsg
            "'PORTRAIT' TEXT," + // 5: portrait
            "'BG_URL' TEXT," + // 6: bgUrl
            "'POST_CONTENT' TEXT," + // 7: postContent
            "'CHAT_SOURCE' TEXT," + // 8: chatSource
            "'RELATION' TEXT," + // 9: relation
            "'TIMESTAMP' INTEGER," + // 10: timestamp
            "'UNREAD_COUNT' INTEGER," + // 11: unreadCount
            "'FAVORITE' INTEGER);"); // 12: favorite
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CONVERSATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Conversation entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String chatId = entity.getChatId();
        if (chatId != null) {
            stmt.bindString(2, chatId);
        }

        String postId = entity.getPostId();
        if (postId != null) {
            stmt.bindString(3, postId);
        }

        String commentId = entity.getCommentId();
        if (commentId != null) {
            stmt.bindString(4, commentId);
        }

        String lastMsg = entity.getLastMsg();
        if (lastMsg != null) {
            stmt.bindString(5, lastMsg);
        }

        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(6, portrait);
        }

        String bgUrl = entity.getBgUrl();
        if (bgUrl != null) {
            stmt.bindString(7, bgUrl);
        }

        String postContent = entity.getPostContent();
        if (postContent != null) {
            stmt.bindString(8, postContent);
        }

        String chatSource = entity.getChatSource();
        if (chatSource != null) {
            stmt.bindString(9, chatSource);
        }

        String relation = entity.getRelation();
        if (relation != null) {
            stmt.bindString(10, relation);
        }

        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(11, timestamp);
        }

        Integer unreadCount = entity.getUnreadCount();
        if (unreadCount != null) {
            stmt.bindLong(12, unreadCount);
        }

        Boolean favorite = entity.getFavorite();
        if (favorite != null) {
            stmt.bindLong(13, favorite ? 1l : 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public Conversation readEntity(Cursor cursor, int offset) {
        Conversation entity = new Conversation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // chatId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // postId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // commentId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // lastMsg
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // portrait
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bgUrl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // postContent
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // chatSource
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // relation
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // timestamp
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // unreadCount
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0 // favorite
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, Conversation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setChatId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPostId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCommentId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLastMsg(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPortrait(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBgUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPostContent(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setChatSource(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRelation(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTimestamp(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setUnreadCount(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setFavorite(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(Conversation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(Conversation entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
