package com.utree.eightysix.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private Long id;
    /**
     * Not-null value.
     */
    private String chatId;
    private String postId;
    private String commentId;
    private String msgId;
    private Long timestamp;
    private String from;
    private Integer type;
    private String content;
    private Integer status;
    private Boolean read;
    private Integer direction;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String chatId, String postId, String commentId, String msgId, Long timestamp, String from, Integer type, String content, Integer status, Boolean read, Integer direction) {
        this.id = id;
        this.chatId = chatId;
        this.postId = postId;
        this.commentId = commentId;
        this.msgId = msgId;
        this.timestamp = timestamp;
        this.from = from;
        this.type = type;
        this.content = content;
        this.status = status;
        this.read = read;
        this.direction = direction;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getChatId() {
        return chatId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    public String getPostId() {
        return postId;
    }

    public void setPostId(String postId) {
        this.postId = postId;
    }

    public String getCommentId() {
        return commentId;
    }

    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getRead() {
        return read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    public Integer getDirection() {
        return direction;
    }

    public void setDirection(Integer direction) {
        this.direction = direction;
    }

}
