package com.utree.eightysix.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONVERSATION.
 */
public class Conversation {

    private Long id;
    /** Not-null value. */
    private String chatId;
    private String postId;
    private String postSource;
    private String postContent;
    private String portrait;
    private String portraitColor;
    private String myPortrait;
    private String myPortraitColor;
    private String bgUrl;
    private String bgColor;
    private String commentId;
    private String commentContent;
    private String relation;
    private String lastMsg;
    private Long timestamp;
    private Long unreadCount;
    private Boolean favorite;

    public Conversation() {
    }

    public Conversation(Long id) {
        this.id = id;
    }

    public Conversation(Long id, String chatId, String postId, String postSource, String postContent, String portrait, String portraitColor, String myPortrait, String myPortraitColor, String bgUrl, String bgColor, String commentId, String commentContent, String relation, String lastMsg, Long timestamp, Long unreadCount, Boolean favorite) {
        this.id = id;
        this.chatId = chatId;
        this.postId = postId;
        this.postSource = postSource;
        this.postContent = postContent;
        this.portrait = portrait;
        this.portraitColor = portraitColor;
        this.myPortrait = myPortrait;
        this.myPortraitColor = myPortraitColor;
        this.bgUrl = bgUrl;
        this.bgColor = bgColor;
        this.commentId = commentId;
        this.commentContent = commentContent;
        this.relation = relation;
        this.lastMsg = lastMsg;
        this.timestamp = timestamp;
        this.unreadCount = unreadCount;
        this.favorite = favorite;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getChatId() {
        return chatId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    public String getPostId() {
        return postId;
    }

    public void setPostId(String postId) {
        this.postId = postId;
    }

    public String getPostSource() {
        return postSource;
    }

    public void setPostSource(String postSource) {
        this.postSource = postSource;
    }

    public String getPostContent() {
        return postContent;
    }

    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }

    public String getPortrait() {
        return portrait;
    }

    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    public String getPortraitColor() {
        return portraitColor;
    }

    public void setPortraitColor(String portraitColor) {
        this.portraitColor = portraitColor;
    }

    public String getMyPortrait() {
        return myPortrait;
    }

    public void setMyPortrait(String myPortrait) {
        this.myPortrait = myPortrait;
    }

    public String getMyPortraitColor() {
        return myPortraitColor;
    }

    public void setMyPortraitColor(String myPortraitColor) {
        this.myPortraitColor = myPortraitColor;
    }

    public String getBgUrl() {
        return bgUrl;
    }

    public void setBgUrl(String bgUrl) {
        this.bgUrl = bgUrl;
    }

    public String getBgColor() {
        return bgColor;
    }

    public void setBgColor(String bgColor) {
        this.bgColor = bgColor;
    }

    public String getCommentId() {
        return commentId;
    }

    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    public String getCommentContent() {
        return commentContent;
    }

    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    public String getRelation() {
        return relation;
    }

    public void setRelation(String relation) {
        this.relation = relation;
    }

    public String getLastMsg() {
        return lastMsg;
    }

    public void setLastMsg(String lastMsg) {
        this.lastMsg = lastMsg;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Long getUnreadCount() {
        return unreadCount;
    }

    public void setUnreadCount(Long unreadCount) {
        this.unreadCount = unreadCount;
    }

    public Boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

}
